### ISSUE TITLE
Running the starter with RabbitMQ does not seem to work

### ISSUE THREAD

**Issue by Zehelein** [node-ts/bus-starter#16]
Hi,

first of all thank you for those libraries! I was looking for quite a long time to have anything in the spirit of NServiceBus that is transport agnostic. So this looks really great!

I tried to adjust the transport mechanism of the starter project to use the RabbitMQ as the transport layer. I tested via the suggested docker container (https://node-ts.github.io/bus/packages/bus-rabbitmq/) and via cloudamqp. 

I changed the `application-container.ts` file for the following (without the RabbitMQ it works):

```ts
import { Container } from "inversify";
import { BusModule } from "@node-ts/bus-core";
import { LoggerModule } from "@node-ts/logger-core";
import { WinstonModule } from "@node-ts/logger-winston";
import { HandlersModule } from "./handlers/handlers-module";
import { BusWorkflowModule } from "@node-ts/bus-workflow";
import {
  BUS_RABBITMQ_SYMBOLS,
  BusRabbitMqModule,
  RabbitMqTransportConfiguration
} from "@node-ts/bus-rabbitmq";

const rabbitConfiguration: RabbitMqTransportConfiguration = {
  queueName: "accounts-application-queue",
  connectionString: "amqp://guest:guest@localhost"
};

export const container = new Container();
container.load(new LoggerModule());
container.load(new BusModule());
container.load(new BusRabbitMqModule());
container.load(new WinstonModule());
container.load(new BusWorkflowModule());
container.load(new HandlersModule());

container
  .bind(BUS_RABBITMQ_SYMBOLS.TransportConfiguration)
  .toConstantValue(rabbitConfiguration);

```

The error I see is the following:

```
TypeError: Cannot read property 'map' of undefined
    at RabbitMqTransport.bindExchangesToQueue (C:\Projects\my-bus-app\node_modules\@node-ts\bus-rabbitmq\dist\rabbitmq-transport.js:81:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RabbitMqTransport.initialize (C:\Projects\my-bus-app\node_modules\@node-ts\bus-rabbitmq\dist\rabbitmq-transport.js:24:9)
    at async ApplicationBootstrap.initialize (C:\Projects\my-bus-app\node_modules\@node-ts\bus-core\dist\application-bootstrap\application-bootstrap.js:23:13)
    at async initialize (C:\Projects\my-bus-app\dist\index.js:21:5)
```

Other than that I did not change anything. Would there be other steps involved that I would need to implement?

Thanks!

P.S. with PostgreSQL as the transport layer it worked. The documentation was a bit off, I created a pull request for it.

**Comment by adenhertog** [comment]
Hey @Zehelein, thanks for the detailed issue report! The problem was outdated dependencies (namely `@node-ts/bus-core` and `@node-ts/bus-workflow`). I've got Greenkeeper set to update these but I must have missed a PR somewhere along the way.

I've put your changes into https://github.com/node-ts/bus-starter/tree/16-rabbitmq-error with the updated packages and it's working fine for me now:

```
...
2020-03-01T01:24:15.807Z info: 	RabbitMQ transport initialized {
  "name": "RabbitMqTransport"
}
2020-03-01T01:24:15.807Z info: 	ServiceBus starting... {
  "name": "ServiceBus"
}
2020-03-01T01:24:15.807Z info: 	Bus application initialized {
  "name": "ApplicationBootstrap"
}
2020-03-01T01:24:15.812Z info: 	StartSirenTest command received, starting siren test... {
  "name": "StartSirenTestHandler",
  "sirenId": "597d0b04-4dc7-454e-9af5-c0d7501de512"
}
...
```

**Comment by Zehelein** [comment]
Thanks for your fast fix! This works now :-)
